### ISSUE TITLE
Уникальное имя файла

### ISSUE THREAD

**Issue by arikaiy** [kirill-dan/uploadimage#1]
https://github.com/kirill-dan/uploadimage/blob/master/src/UploadImage.php#L149 Можно использовать UUID, в ларе вроде так если сделали.

**Comment by kirill-dan** [comment]
Я пока вынес создание уникального имени в отдельный метод. Хотел, чтобы по файлу еще была видна принадлежность к типу контента. Позже, может переделаю.
